### PR TITLE
3 - fix sysctl only_if order

### PR DESCRIPTION
**Pull request by romkey**
made only_if first

### CODE REVIEW

**Comment by jherdman** [comment]
No es bueno :(

**Comment by romkey** [comment]
"Computer. What is the nature of `value`?"

Argh. It's worse than that. If `node['watchman']` isn't defined the guard will bomb.

**Comment by jherdman** [comment]
Perhaps the attributes should be modified to something like this:

``` ruby
default['watchman'] = {}
default['watchman']['version'] = ....
```

**Comment by romkey** [comment]
That's what I'm thinking too. I'll tinker with it and update the PR later.

**Comment by romkey** [comment]
That didn't fix it. Trying something else.

**Pull request merged**
